### ISSUE TITLE
Inference Speed

### ISSUE THREAD

**Issue by arraycat** [jimmy-dq/DropTrack#4]
Why is DropTrack so much slower than OStrack? 

When using OSTrack-256 for testing, it can reach 110+FPS on GOT-10K, but DropTrack-256 can only reach 55+FPS, which is even slower than OSTrack-384's 75+FPS. I am using a RTX 3080 (10G).

**Comment by jimmy-dq** [comment]
@arraycat, thanks for your report. Actually, we add some additional GPU variable operations in https://github.com/jimmy-dq/DropTrack/blob/4364304f64942b9ef54fac4db9a8ba2ccfc3ee53/lib/test/evaluation/tracker.py#L65 
 and in L153-L156, to improve GPU utility and avoid terminating by systems when submitting to the server. You can just safely remove these lines to further improve the inference speed. 
In addition, the provided models are trained with `vitb_384_mae_ce_32x4_got10k_ep100` or `vitb_384_mae_ce_32x4_ep300`, the inference speed in 384 should be similar w/ OSTrack, since we use the same inference code after deleting the above lines. You can test OSTrack-384 in the same platform for fair comparison.

**Comment by arraycat** [comment]
Thanks for your reply, the problem is solved.

**Comment by arraycat** [comment]
By the way, have you trained the model of vitb_256_mae_ce_32x4_ep300, can you provide the download link?

**Comment by jimmy-dq** [comment]
> By the way, have you trained the model of vitb_256_mae_ce_32x4_ep300, can you provide the download link?
Not yet. But you could use the downloaded pre-trained model as the initialization for vitb_256_mae_ce_32x4_ep300.
