### ISSUE TITLE
论文中的公式（4）

### ISSUE THREAD

**Issue by tangsirfly** [jimmy-dq/DropTrack#5]
您好
问题1：论文中的公式4为什么要用一个时间匹配概率和标准化的空间重要性相乘，这两个变量之间有什么联系吗？
问题2：然后论文中提到 “当Wi,j较大时，第i个查询令牌具有较好的帧间匹配性“ 帧间的匹配性是由ftem函数直接影响的，为什么乘上标准化的空间重要性之后也是 Wi,j越大，帧间爱你的相关性越好？
期待您的回答，谢谢！

**Comment by jimmy-dq** [comment]
Hi，
Sry for the late reply. 
**For the 1st question**, we aim to find reconstructed query patches which heavily relied on their spatial neighbouring cues for reconstruction. However, if we only use the spatial importance for measurement, it is not reliable since these patches in the temporal frame may be occluded, which cannot be leveraged for reconstructing the patches in the same frame, so we consider both spatial&temporal scores for measument.
**For the 2nd question**, when Wi,j is large, it indicates the large probability to perform dropout, which is both measured by the temporal matching score and spatial importance.
